#name of the workflow. it is just a name.

name: "Terraform"

#if there is any push to my main branch

on:
  push:
      branches:
            - main

# jobs sections

jobs:
  terraform:
      name: "Terraform"
      runs-on: ubuntu-latest


      env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

#the default section 
      defaults:
        run:
            working-directory: src
      steps:
#checkout is to clone the repository to remote server and do the actions/execute the code. it copies everything and pastes it into ubuntu
          - name: Checkout
            uses: actions/checkout@v2

#command to setup terraform
          - name: Setup terraform
            uses: hashicorp/setup-terraform@v1
            with:
              terraform_version: 1.0.1
              terraform_wrapper: false

          - name: Terraform Initialization
            id: init
            run: terraform init  # No `-auto-approve` here, just `terraform init`

          - name: Terraform Planning
            id: plan
            run: terraform plan  # No `-auto-approve` needed for planning

          - name: Terraform Apply Infrastructure
            run: terraform apply -auto-approve  # Correct use of `-auto-approve`


          #- name: Terraform apply infrastructure
            #run: terraform apply -auto-approve

          - name: Terraform destroy infrastructure
            run: terraform destroy -auto-approve
